name: PR Checks
on:
  pull_request:
    branches: master
    paths:
      - '**/*.py'
      - 'pyproject.toml'
      - 'poetry.lock'
jobs:
  lint:
    uses: ./.github/workflows/linting.yml
    name: Linting
  test:
    uses: ./.github/workflows/testing.yml
    name: Testing
