name: PR Checks
on:
  pull_request:
    branches: ["master"]
    paths:
      - '**/*.py'
      - 'pyproject.toml'
      - 'poetry.lock'
jobs:
  version-check:
    uses: ./.github/workflows/new-version-check.yml
    name: Check Version on Python Changes
  lint:
    uses: ./.github/workflows/linting.yml
    name: Linting
    with:
      system: "ubuntu-22.04"
      python-version: "3.10"
  test:
    uses: ./.github/workflows/testing.yml
    name: Testing
    strategy:
      fail-fast: false
      matrix:
        system: [ "ubuntu-20.04", "ubuntu-22.04" ]
        python-version: [ "3.10", "3.11" ]
    with:
      system: ${{ matrix.system }}
      python-version: ${{ matrix.python-version }}

