name: Tests
on:
  workflow_call:
    inputs:
      system:
        description: 'System to run on'
        required: false
        type: string
        default: ubuntu-20.04
      command:
        description: 'Command to run'
        required: false
        type: string
        default: "make tests"
      python-version:
        description: 'Python version to use'
        required: false
        type: string
        default: "3.10"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.system }}-${{ inputs.python-version }}-${{ inputs.command }}
  cancel-in-progress: true
jobs:
  test_pr:
    name: Tests
    runs-on: ${{ inputs.system }}
    steps:
      - name: Getting code
        uses: actions/checkout@v4
      - name: Getting Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Load cached poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: ${{ runner.os }}-poetry-${{ steps.setup-python.outputs.python-version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-pip-${{ hashFiles('poetry.lock') }}-${{ steps.setup-python.outputs.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
          version: 1.4.2

      - name: Installing dependencies
        run: poetry install
      - name: Running tests
        run: ${{ inputs.command }}
